Update to 0ad-0.0.13.

diff --git a/games/0ad/patches/patch-build_workspaces_update-workspaces_sh b/games/0ad/patches/patch-build_workspaces_update-workspaces_sh
--- a/games/0ad/patches/patch-build_workspaces_update-workspaces_sh
+++ b/games/0ad/patches/patch-build_workspaces_update-workspaces_sh
@@ -1,13 +1,13 @@
 $OpenBSD$
 Don't build bundled libraries during configure.
---- build/workspaces/update-workspaces.sh.orig	Sat Nov 10 00:38:01 2012
-+++ build/workspaces/update-workspaces.sh	Sat Nov 10 00:38:06 2012
-@@ -67,7 +67,7 @@ echo "Updating bundled third-party dependencies..."
- echo
+--- build/workspaces/update-workspaces.sh.orig.port	Thu Apr  4 01:32:27 2013
++++ build/workspaces/update-workspaces.sh	Thu Apr  4 01:35:07 2013
+@@ -77,7 +77,7 @@ if [ "`uname -s`" != "Darwin" ]; then
+   echo
  
- # Build/update bundled external libraries
--(cd ../../libraries/fcollada/src && ${MAKE} ${JOBS}) || die "FCollada build failed"
-+#(cd ../../libraries/fcollada/src && ${MAKE} ${JOBS}) || die "FCollada build failed"
- echo
- if [ "$with_system_mozjs185" = "false" ]; then
-   (cd ../../libraries/spidermonkey && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "SpiderMonkey build failed"
+   # Build/update bundled external libraries
+-  (cd ../../libraries/source/fcollada/src && ${MAKE} ${JOBS}) || die "FCollada build failed"
++#  (cd ../../libraries/source/fcollada/src && ${MAKE} ${JOBS}) || die "FCollada build failed"
+   echo
+   if [ "$with_system_mozjs185" = "false" ]; then
+     (cd ../../libraries/source/spidermonkey && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "SpiderMonkey build failed"
