update to munin-2.999.11

diff --git a/net/munin3/patches/patch-script_munin-check b/net/munin3/patches/patch-script_munin-check
--- a/net/munin3/patches/patch-script_munin-check
+++ b/net/munin3/patches/patch-script_munin-check
@@ -1,6 +1,7 @@
 $OpenBSD$
---- script/munin-check.orig	Sun Sep  4 23:04:49 2016
-+++ script/munin-check	Fri Nov  4 11:44:13 2016
+Index: script/munin-check
+--- script/munin-check.orig
++++ script/munin-check
 @@ -1,4 +1,4 @@
 -#!/bin/bash
 +#!@@GOODSH@@
@@ -15,14 +16,14 @@ $OpenBSD$
 +function usage {
      echo "Usage: munin-check [options]
  Options:
--   -h|--help		Show this help.
--   -v|--verbose		Be verbose.
--   -f|--fix-permissions Fix the permissions of the munin dirs and files.
--   			Needs superuser rights.
-+   -h		Show this help.
-+   -v		Be verbose.
-+   -f		Fix the permissions of the munin dirs and files.
-+   		Needs superuser rights.
+-   -h|--help             Show this help.
+-   -v|--verbose          Be verbose.
+-   -f|--fix-permissions  Fix the permissions of the munin dirs and files.
+-                         Needs superuser rights.
++   -h	Show this help.
++   -v	Be verbose.
++   -f	Fix the permissions of the munin dirs and files.
++	Needs superuser rights.
  
  Please don't use this script if you are using 'graph_strategy cgi'!
  It doesn't care about the right permissions for www-data yet...
@@ -33,22 +34,30 @@ $OpenBSD$
 -TEMP=$(getopt -o fhv --long fix-permissions,help,verbose -n 'munin-check' -- "$@")
 +TEMP=$(getopt fhv $*)
  
+ # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
-     echo "Terminating..." >&2
-@@ -45,9 +45,9 @@ eval set -- "$TEMP"
+@@ -47,16 +47,16 @@ PLEASE_FIXME="false"
  VERBOSE="false"
  while :; do
      case "$1" in
--	-h|--help) usage ; exit 0; shift ;;
--	-v|--verbose) VERBOSE="true"; shift;;
--	-f|--fix-permissions) PLEASE_FIXME="true" ;  shift ;;
-+	-h usage ; exit 0; shift ;;
-+	-v VERBOSE="true"; shift;;
-+	-f PLEASE_FIXME="true" ;  shift ;;
- 	--) shift ; break ;;
- 	*) echo "Internal error!" ; exit 1 ;;
+-        -h|--help) usage ; exit 0; shift ;;
+-        -v|--verbose) VERBOSE="true"; shift;;
+-        -f|--fix-permissions) PLEASE_FIXME="true" ;  shift ;;
++        -h usage ; exit 0; shift ;;
++        -v VERBOSE="true"; shift;;
++        -f PLEASE_FIXME="true" ;  shift ;;
+         --) shift ; break ;;
+         *) echo "Internal error!" ; exit 1 ;;
      esac
-@@ -55,7 +55,7 @@ done
+ done
+ 
+ 
+-function msg_info() {
++function msg_info {
+     local message="$1"
+     if [ "$VERBOSE" = "true" ]; then
+         echo "$message"
+@@ -66,7 +66,7 @@ function msg_info() {
  
  ####
  # sets owner to "@@USER@@"
@@ -57,28 +66,28 @@ $OpenBSD$
      fix_object=$1; shift
      fix_owner=$1; shift
  
-@@ -73,7 +73,7 @@ function fix_owner() {
+@@ -85,7 +85,7 @@ function fix_owner() {
+ 
  ####
  # check if "@@USER@@" is owner, if PLEASE_FIXME set it calls fix_owner()
- 
 -function owner_ok() {
 +function owner_ok {
      object=$1; shift || exit 1
      correctowner=$1; shift || exit 1
  
-@@ -95,6 +95,11 @@ function owner_ok() {
- 	    "lost+found") return 0;;
- 	esac
+@@ -107,6 +107,11 @@ function owner_ok() {
+             "lost+found") return 0;;
+         esac
  
-+	# cgi-tmp owner should be www
-+	case $object in
-+	    "cgi-tmp") correctowner=www;
-+	esac
++       # cgi-tmp owner should be www
++       case $object in
++           "cgi-tmp") correctowner=www;
++       esac
 +
- 	# ... and then dive into it
- 	for subobject in $object/*; do
- 		owner_ok $subobject $correctowner
-@@ -103,7 +108,7 @@ function owner_ok() {
+         # ... and then dive into it
+         for subobject in "$object"/*; do
+             owner_ok "$subobject" "$correctowner"
+@@ -115,7 +120,7 @@ function owner_ok() {
  }
  
  
@@ -87,16 +96,16 @@ $OpenBSD$
      object=$1; shift || exit 1
      correctperm=$1; shift || exit 1
  
-@@ -146,12 +151,20 @@ for dir in @@DBDIR@@/*; do
- 	*/plugin-state)
- 	    continue;;
+@@ -162,12 +167,20 @@ for dir in "@@DBDIR@@"/*; do
+         */plugin-state)
+             continue;;
      esac
 +    case $dir in
-+	*/cgi-tmp)
-+	    continue;;
++       */cgi-tmp)
++           continue;;
 +    esac
      echo "check $dir"
-     owner_ok $dir @@USER@@
+     owner_ok "$dir" "@@USER@@"
  done
  
 +echo "check @@DBDIR@@/cgi-tmp"
@@ -107,5 +116,5 @@ $OpenBSD$
 +norec=yes owner_ok @@LOGDIR@@ @@PLUGINUSER@@
 +norec=yes perm_ok @@LOGDIR@@ 775
  
- norec=yes owner_ok @@DBDIR@@ @@USER@@
- norec=yes perm_ok @@DBDIR@@ 755
+ norec=yes owner_ok "@@DBDIR@@" "@@USER@@"
+ norec=yes perm_ok "@@DBDIR@@" 755
